package io.slotum.backend.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    // Codes

    // User
    INVALID_USER_ID(HttpStatus.BAD_REQUEST),
    INVALID_USER_SURNAME(HttpStatus.BAD_REQUEST),
    INVALID_USER_FIRSTNAME(HttpStatus.BAD_REQUEST),
    INVALID_USER_EMAIL(HttpStatus.BAD_REQUEST),
    USER_EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
    INVALID_USER_PASSWORD(HttpStatus.BAD_REQUEST),
    INVALID_USER_PHONE(HttpStatus.BAD_REQUEST),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),

    // Organization
    INVALID_ORGANIZATION_ID(HttpStatus.BAD_REQUEST),
    TOO_LONG_ORGANIZATION_NAME(HttpStatus.BAD_REQUEST),
    EMPTY_ORGANIZATION_NAME(HttpStatus.BAD_REQUEST),
    EMPTY_ORGANIZATION_DESCRIPTION(HttpStatus.BAD_REQUEST),
    TOO_LONG_ORGANIZATION_DESCRIPTION(HttpStatus.BAD_REQUEST),
    INVALID_ORGANIZATION_GRADE(HttpStatus.BAD_REQUEST),
    ORGANIZATION_ALREADY_EXISTS(HttpStatus.CONFLICT),

    // Specialist
    INVALID_SPECIALIST_USER_ID(HttpStatus.BAD_REQUEST),
    EMPTY_SPECIALIST_DESCRIPTION(HttpStatus.BAD_REQUEST),
    TOO_LONG_SPECIALIST_DESCRIPTION(HttpStatus.BAD_REQUEST),
    INVALID_SPECIALIST_GRADE(HttpStatus.BAD_REQUEST),
    SPECIALIST_ALREADY_EXISTS(HttpStatus.CONFLICT),

    // Appointment
    INVALID_APPOINTMENT_ID(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_STARTS_AT(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_ENDS_AT(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_TIME_RANGE(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_STATUS(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_SPECIALIST_ID(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_CUSTOMER_ID(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_ORGANIZATION_ID(HttpStatus.BAD_REQUEST),
    ;

    private final HttpStatus httpStatus;

    ErrorCode(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }
}
