package io.slotum.backend.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    // Codes

    // Auth
    AUTH_INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),

    // User
    INVALID_USER_ID(HttpStatus.BAD_REQUEST),
    INVALID_USER_SURNAME(HttpStatus.BAD_REQUEST),
    INVALID_USER_FIRSTNAME(HttpStatus.BAD_REQUEST),
    INVALID_USER_EMAIL(HttpStatus.BAD_REQUEST),
    USER_EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
    INVALID_USER_PASSWORD(HttpStatus.BAD_REQUEST),
    INVALID_USER_PHONE(HttpStatus.BAD_REQUEST),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),

    // Organization
    INVALID_ORGANIZATION_ID(HttpStatus.BAD_REQUEST),
    TOO_LONG_ORGANIZATION_NAME(HttpStatus.BAD_REQUEST),
    EMPTY_ORGANIZATION_NAME(HttpStatus.BAD_REQUEST),
    EMPTY_ORGANIZATION_DESCRIPTION(HttpStatus.BAD_REQUEST),
    TOO_LONG_ORGANIZATION_DESCRIPTION(HttpStatus.BAD_REQUEST),
    INVALID_ORGANIZATION_GRADE(HttpStatus.BAD_REQUEST),
    ORGANIZATION_ALREADY_EXISTS(HttpStatus.CONFLICT),
    ORGANIZATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    ORGANIZATION_MEMBERSHIP_ALREADY_EXISTS(HttpStatus.CONFLICT),
    ORGANIZATION_MEMBERSHIP_NOT_FOUND(HttpStatus.NOT_FOUND),

    // Specialist
    INVALID_SPECIALIST_USER_ID(HttpStatus.BAD_REQUEST),
    EMPTY_SPECIALIST_DESCRIPTION(HttpStatus.BAD_REQUEST),
    TOO_LONG_SPECIALIST_DESCRIPTION(HttpStatus.BAD_REQUEST),
    INVALID_SPECIALIST_GRADE(HttpStatus.BAD_REQUEST),
    SPECIALIST_ALREADY_EXISTS(HttpStatus.CONFLICT),
    SPECIALIST_NOT_FOUND(HttpStatus.NOT_FOUND),

    // Slot
    INVALID_SLOT_ID(HttpStatus.BAD_REQUEST),
    INVALID_SLOT_STARTS_AT(HttpStatus.BAD_REQUEST),
    INVALID_SLOT_ENDS_AT(HttpStatus.BAD_REQUEST),
    INVALID_SLOT_TIME_RANGE(HttpStatus.BAD_REQUEST),
    INVALID_SLOT_STATUS(HttpStatus.BAD_REQUEST),
    INVALID_SLOT_SPECIALIST_ID(HttpStatus.BAD_REQUEST),
    INVALID_SLOT_CUSTOMER_ID(HttpStatus.BAD_REQUEST),
    INVALID_SLOT_ORGANIZATION_ID(HttpStatus.BAD_REQUEST),
    SLOT_ALREADY_EXISTS(HttpStatus.CONFLICT),
    SLOT_NOT_FOUND(HttpStatus.NOT_FOUND),
    SLOT_OVERLAPPING(HttpStatus.CONFLICT),

    // Slot request
    INVALID_APPOINTMENT_REQUEST_ID(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_REQUEST_SLOT_ID(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_REQUEST_CUSTOMER_ID(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_REQUEST_STATUS(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_REQUEST_MESSAGE(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_REQUEST_CREATED_AT(HttpStatus.BAD_REQUEST),
    INVALID_APPOINTMENT_REQUEST_DECIDED_AT(HttpStatus.BAD_REQUEST),
    APPOINTMENT_REQUEST_ALREADY_EXISTS(HttpStatus.CONFLICT),
    APPOINTMENT_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND),
    APPOINTMENT_REQUEST_NOT_PENDING(HttpStatus.CONFLICT),
    APPOINTMENT_REQUEST_SLOT_NOT_FREE(HttpStatus.CONFLICT),
    APPOINTMENT_REQUEST_FORBIDDEN(HttpStatus.FORBIDDEN),
    ;

    private final HttpStatus httpStatus;

    ErrorCode(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }
}
