package io.slotum.backend.error;

public enum ErrorCode {
    // Codes

    // User
    INVALID_USER_ID,
    INVALID_USER_SURNAME,
    INVALID_USER_FIRSTNAME,
    INVALID_USER_EMAIL,
    USER_EMAIL_ALREADY_EXISTS,
    INVALID_USER_PASSWORD,
    INVALID_USER_PHONE,

    // Organization
    INVALID_ORGANIZATION_ID,
    TOO_LONG_ORGANIZATION_NAME,
    EMPTY_ORGANIZATION_NAME,
    EMPTY_ORGANIZATION_DESCRIPTION,
    TOO_LONG_ORGANIZATION_DESCRIPTION,
    INVALID_ORGANIZATION_GRADE,
    ORGANIZATION_ALREADY_EXISTS,

    // Specialist
    INVALID_SPECIALIST_USER_ID,
    EMPTY_SPECIALIST_DESCRIPTION,
    TOO_LONG_SPECIALIST_DESCRIPTION,
    INVALID_SPECIALIST_GRADE,

    // Appointment
    INVALID_APPOINTMENT_ID,
    INVALID_APPOINTMENT_STARTS_AT,
    INVALID_APPOINTMENT_ENDS_AT,
    INVALID_APPOINTMENT_TIME_RANGE,
    INVALID_APPOINTMENT_STATUS,
    INVALID_APPOINTMENT_SPECIALIST_ID,
    INVALID_APPOINTMENT_CUSTOMER_ID,
    INVALID_APPOINTMENT_ORGANIZATION_ID,
}
