spring.application.name=backend

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/slotum
spring.datasource.username=postgres
spring.datasource.password=dima14112005

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Hibernate
spring.jpa.hibernate.ddl-auto=none