-- liquibase formatted sql

-- changeset dmitriyBreyfogel:031-insert-permissions
INSERT INTO permissions (code, description) VALUES
    ('CREATE_OWN_SPECIALIST', 'Can create own specialist profile'),
    ('CREATE_ANY_SPECIALIST', 'Can create specialist for any user'),
    ('VIEW_ANY_SPECIALIST', 'Can view any specialist'),
    ('VIEW_SPECIALIST_ORGANIZATIONS', 'Can view specialist organizations'),
    ('DELETE_ANY_SPECIALIST', 'Can delete any specialist'),
    ('DELETE_ALL_SPECIALISTS', 'Can delete all specialists'),
    ('CREATE_SLOT', 'Can create slots'),
    ('VIEW_SLOT', 'Can view slot details'),
    ('VIEW_ANY_SLOTS', 'Can view all slots'),
    ('MANAGE_ANY_SLOTS', 'Can delete any slot'),
    ('DELETE_ALL_SLOTS', 'Can delete all slots'),
    ('CREATE_BOOKING', 'Can create booking request'),
    ('VIEW_OWN_BOOKINGS', 'Can view own bookings'),
    ('VIEW_ANY_BOOKINGS', 'Can view any bookings'),
    ('ACCEPT_BOOKING', 'Can accept booking request'),
    ('REJECT_BOOKING', 'Can reject booking request'),
    ('CANCEL_OWN_BOOKING', 'Can cancel own booking'),
    ('CREATE_OWN_ORGANIZATION', 'Can create own organization'),
    ('CREATE_ANY_ORGANIZATION', 'Can create any organization'),
    ('VIEW_OWN_ORGANIZATIONS', 'Can view own organizations'),
    ('VIEW_ORGANIZATIONS_FOR_BOOKING', 'Can view organizations for booking'),
    ('VIEW_ANY_ORGANIZATION', 'Can view any organization details'),
    ('MANAGE_OWN_ORGANIZATION', 'Can manage own organization'),
    ('MANAGE_ANY_ORGANIZATION', 'Can manage any organization'),
    ('ADD_SPECIALIST_TO_ORG', 'Can add specialist to organization'),
    ('VIEW_ORG_SPECIALISTS', 'Can view organization specialists'),
    ('DELETE_ALL_ORGANIZATIONS', 'Can delete all organizations'),
    ('VIEW_USERS', 'Can view users'),
    ('MANAGE_USERS', 'Can manage users'),
    ('VIEW_ROLES', 'Can view roles'),
    ('MANAGE_ROLES', 'Can manage roles'),
    ('VIEW_PERMISSIONS', 'Can view permissions'),
    ('MANAGE_PERMISSIONS', 'Can manage permissions'),
    ('VIEW_RESOURCES', 'Can view resources'),
    ('MANAGE_RESOURCES', 'Can manage resources'),
    ('VIEW_REFRESH_TOKENS', 'Can view refresh tokens'),
    ('REVOKE_REFRESH_TOKENS', 'Can revoke refresh tokens');